version: "3"
services:
  example:
    image: alpine
    command: "env"
    environment:
      - "FOO=$FOO"
      - "BAR=$BAR"
      - "BAZ=$BAZ"
    networks:
      - example
networks:
  example:
    external:
      name: example
